### ISSUE TITLE
Mock data should have meaning

### ISSUE THREAD

**Issue by zachfedor** [ts-cset/gold-portal#26]
https://github.com/ts-cset/gold-portal/blob/f83905f8df590f3d67599d34ad82c132e70f13fe/tests/data.sql#L12-L13

If the mock data is meaningful, it help documents how the app should actually work. Putting nonsense data in doesn't help you understand how the app works in the real world by users.

**Comment by LazaroFranco** [comment]
In the pull request of #31, this issue has been resolved.
